### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-soap.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "codedredd/laravel-soap": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by bretto36** [comment]
@CodeDredd  Any chance of this getting merged? We are wanting to use L10 and seems to have issues with the illuminate stuff

Problem 1
    - Root composer.json requires codedredd/laravel-soap ^3.0.2 -> satisfiable by codedredd/laravel-soap[v3.0.2].
    - Only one of these can be installed: illuminate/contracts[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.6, v10.0.0, ..., v10.8.0], laravel/framework[v10.8.0]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.
    - codedredd/laravel-soap v3.0.2 requires illuminate/contracts ^9.0 -> satisfiable by illuminate/contracts[v9.0.0, ..., v9.52.6].
    - Root composer.json requires laravel/framework ^10.8 -> satisfiable by laravel/framework[v10.8.0].

**Comment by CodeDredd** [comment]
@bretto36 Have you tried the new version?
I merged already an 10.x PR. But i am merging this too. Just need to verify if the changes are correct now

**Comment by bretto36** [comment]
@CodeDredd  ah i had to be explicit to use the -beta branch in my composer json file. Laravel changed minimum stability to "stable" as the default

Thank you for attending to my query so quickly

**Pull request merged**
